name: test-on-act

on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [ -d /github/home -a ! -e /home/runner ]; then
            ln -s /github/home /home/runner
          fi
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@master
      - run: bundle install
      - run: bundle exec rake
